## Load metadata

```{r}
meta_choroid <- read.csv(file.path("..", "meta", "choroid_meta.csv"), header = TRUE)
```

## Load and prepare GEX data

### Prepare list with Seurat objects

```{r}
# set up output list
objs <- list()

# pull sample names of interest
sample_names <- unique(meta_choroid$sample_name)

# create or pull each object
  for (sample in sample_names) {
    cat(sample, "\n")

    # metadata info
    # you should have only one row after this point, so unique()'s are omitted
    meta_sample <- dplyr::filter(meta_choroid, sample_name == sample)

    # read in the data
    data_GEX <- Read10X_h5(file.path(path_data_GEX,
                                  meta_sample$sample_name,
                                  #"outs",
                                  "filtered_feature_bc_matrix.h5"))
    
    # rename sample
    sample <- gsub("_RNA", "", sample)
    
    # create the Seurat object (assay = "RNA")
    obj <- CreateSeuratObject(counts = data_GEX$`Gene Expression`, project = sample)

    # Remove the "-1" suffix from cell barcodes
    cell_names <- colnames(obj)
    cell_names <- gsub("-1$", "", cell_names)
    colnames(obj) <- cell_names        
    
    # add in the sample name to keep unique cell names during combination later
    obj <- RenameCells(obj, add.cell.id = sample)
    obj$cell_id_unique <- colnames(obj) # unique barcodes

    # add useful metadata
    obj$"percent.mt" <- PercentageFeatureSet(obj, pattern = "^MT-") # calculate pct of mitochondrial genes
    obj$sample_name <- meta_sample$sample_name
    obj$sample_final <- meta_sample$sample_final
    obj$subject_id <- meta_sample$subject_id
    obj$sex <- meta_sample$sex
    obj$age <- meta_sample$age
    obj$race <- meta_sample$race
    obj$HIV_status <- meta_sample$HIV_status
    obj$tissue <- meta_sample$tissue
    obj$data_type <- meta_sample$data_type

    # calculate percentage of ribosomal genes
    #ribosomal_genes <- grep(pattern = "^RPS|^RPL", x = rownames(obj), value = TRUE)
    ribosomal_genes <- grep(pattern = "^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA", x = rownames(obj), value = TRUE) 
    ribosomal_genes <- grep(pattern = "[BK-]|AP|[[:digit:]](.+)L", x = ribosomal_genes, invert = TRUE, value = TRUE)
    ribosomal_genes <- ribosomal_genes[ribosomal_genes %in% rownames(obj)]
    obj$"percent.ribo" <- PercentageFeatureSet(obj, features = ribosomal_genes)
        
    # save in the appropriate location
    objs[[sample]] <- obj
  }

# remove unnecessary objects
rm(data_GEX, meta_sample, obj, cell_names, sample, sample_names, ribosomal_genes)
```

### Merge Seurat objects into one object (without integration step)

```{r}
# merge samples (Seurat objects) without integration
gex_choroid <- merge(x = objs[[1]], objs[-1] )

# join layers without integration
gex_choroid[["RNA"]] <- JoinLayers(gex_choroid[["RNA"]])

# calculate total number of cells before QC filtering for expected doublet rate calculation
dbr_expected <- gex_choroid@meta.data %>% 
                      group_by(sample_name) %>% 
                      summarize(total_count = n(), .groups = "drop") %>% 
                      mutate(exp_dbr_0.08 = total_count*0.8/1000,    # for a rate of 0.8% per 1000 captured cells
                             exp_dbr_0.1 = total_count*1/1000)       # for a rate of 1% per 1000 captured cells
```

### Add useful metadata

```{r}
# transform subject_id to character
gex_choroid@meta.data$subject_id <- as.character(gex_choroid@meta.data$subject_id)

# add viremic state
gex_choroid@meta.data <- gex_choroid@meta.data %>%
                              mutate(HIV_status_det = case_when(
                                subject_id %in% c("7102417477", "7102908282", "mhbb742") ~ "control",
                                subject_id %in% c("10269", "20033", "mhb800") ~ "HIV_suppressed",
                                subject_id %in% c("30022", "6801006868", "7102096765") ~ "HIV_viremic", 
                                TRUE ~ NA))
```

### Metrics summary

```{r}
# create table with GEX metrics
metrics_summary <- create_metrics_summary_arc(meta = meta_choroid, path_data_specific = file.path(path_data_GEX), data_types = "GEX")

# clean up
rm(path_data_GEX)
```

```{r}
# transform values of column ValidUMI to numeric for plotting
metrics_summary$ValidUMI <- as.numeric(gsub("%", "", metrics_summary$ValidUMI))  # for ARC
names(metrics_summary)[names(metrics_summary) == "ValidUMI"] <- "ValidUMI_pct" # for ARC

# transform values to numeric for plotting
# ValidBarcodes
metrics_summary$ValidBarcodes <- as.numeric(gsub("%", "", metrics_summary$ValidBarcodes))
names(metrics_summary)[names(metrics_summary) == "ValidBarcodes"] <- "ValidBarcodes_pct"

# ReadsInCells
metrics_summary$ReadsInCells <- as.numeric(gsub("%", "", metrics_summary$ReadsInCells))
names(metrics_summary)[names(metrics_summary) == "ReadsInCells"] <- "ReadsInCells_pct"

# IntronicRegions
metrics_summary$IntronicRegions <- as.numeric(gsub("%", "", metrics_summary$IntronicRegions))
names(metrics_summary)[names(metrics_summary) == "IntronicRegions"] <- "IntronicRegions_pct"

# ExonicRegions
metrics_summary$ExonicRegions <- as.numeric(gsub("%", "", metrics_summary$ExonicRegions))
names(metrics_summary)[names(metrics_summary) == "ExonicRegions"] <- "ExonicRegions_pct"

# TranscriptomeMapping
metrics_summary$TranscriptomeMapping <- as.numeric(gsub("%", "", metrics_summary$TranscriptomeMapping))
names(metrics_summary)[names(metrics_summary) == "TranscriptomeMapping"] <- "TranscriptomeMapping_pct"

# Q30 bases in read 2
metrics_summary$Q30basesRead2 <- as.numeric(gsub("%", "", metrics_summary$Q30basesRead2))
names(metrics_summary)[names(metrics_summary) == "Q30basesRead2"] <- "Q30basesRead2_pct"

# AntisenseMapping
metrics_summary$AntisenseMapping <- as.numeric(gsub("%", "", metrics_summary$AntisenseMapping))
names(metrics_summary)[names(metrics_summary) == "AntisenseMapping"] <- "AntisenseMapping_pct"
```

### Metrics plots

```{r}
# Number of cells
p <- ggplot(metrics_summary, aes(x = sample_name, y = EstimatedNumberofCells, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Number of Cells", 
       x = "Samples", y = "Numbers of Cells") +
  scale_fill_manual(values = col_choroid) +
  geom_hline(yintercept = 500, linetype = "dashed", color = "red") +
  theme_bw + labels_standard + labels_rotate_x

p1 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# Read counts
p <- ggplot(metrics_summary, aes(x = sample_name, y = NumberofReads, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Number of Read Counts", 
       x = "Samples", y = "Numbers of Reads") +
  scale_fill_manual(values = col_choroid) +
  theme_bw + labels_standard + labels_rotate_x

p2 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# Read counts per cell
p <- ggplot(metrics_summary, aes(x = sample_name, y = MeanReadsPerCell, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Number of Read Counts Per Cell", 
       x = "Samples", y = "Numbers of Reads Per Cell (median)") +
  scale_fill_manual(values = col_choroid) +
  geom_hline(yintercept = 20000, linetype = "dashed", color = "red") + 
  theme_bw + labels_standard + labels_rotate_x

p3 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# Fraction of Reads in Cell
p <- ggplot(metrics_summary, aes(x = sample_name, y = ReadsInCells_pct, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Reads In Cell", 
       x = "Samples", y = "Reads In Cell (%)") +
  scale_fill_manual(values = col_choroid) +
  geom_hline(yintercept = 0.7, linetype = "dashed", color = "red") + 
  theme_bw + labels_standard + labels_rotate_x

p4 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# Total number of genes
p <- ggplot(metrics_summary, aes(x = sample_name, y = TotalGenes, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Total number of Genes", 
       x = "Samples", y = "Total Numbers of Genes") +
  scale_fill_manual(values = col_choroid) +
  theme_bw + labels_standard + labels_rotate_x

p5 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# Genes per cell
p <- ggplot(metrics_summary, aes(x = sample_name, y = MedianGenesPerCell, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Number of Genes Per Cell", 
       x = "Samples", y = "Numbers of Genes Per Cell (median)") +
  scale_fill_manual(values = col_choroid) +
  geom_hline(yintercept = 400, linetype = "dashed", color = "red") + 
  theme_bw + labels_standard + labels_rotate_x

p6 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# UMI per cell
p <- ggplot(metrics_summary, aes(x = sample_name, y = MedianUMIPerCell, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Number of UMI Counts Per Cell", 
       x = "Samples", y = "Numbers of UMI Counts Per Cell (median)") +
  scale_fill_manual(values = col_choroid) +
  geom_hline(yintercept = 200, linetype = "dashed", color = "red") + 
  theme_bw + labels_standard + labels_rotate_x

p7 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# Q30 bases in read 2
p <- ggplot(metrics_summary, aes(x = sample_name, y = Q30basesRead2_pct, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Q30 bases in read 2", 
       x = "Samples", y = "Q30 bases in read 2 (%)") +
  scale_fill_manual(values = col_choroid) +
  theme_bw + labels_standard + labels_rotate_x

p8 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())
```

```{r}
# Intronic regions
p <- ggplot(metrics_summary, aes(x = sample_name, y = IntronicRegions_pct, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Reads Mapped to Intronic Regions", 
       x = "Samples", y = "Intronic Regions (%)") +
  scale_fill_manual(values = col_choroid) +
  geom_hline(yintercept = 0.2, linetype = "dashed", color = "red") + 
  theme_bw + labels_standard + labels_rotate_x

p9 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# Exonic regions
p <- ggplot(metrics_summary, aes(x = sample_name, y = ExonicRegions_pct, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Reads Mapped to Exonic Regions", 
       x = "Samples", y = "Exonic Regions (%)") +
  scale_fill_manual(values = col_choroid) +
  geom_hline(yintercept = 0.2, linetype = "dashed", color = "red") + 
  theme_bw + labels_standard + labels_rotate_x

p10 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# Mapping to transcriptome
p <- ggplot(metrics_summary, aes(x = sample_name, y = TranscriptomeMapping_pct, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Reads Mapped to Transcriptome", 
       x = "Samples", y = "Reads Mapped to Transcriptome (%)") +
  scale_fill_manual(values = col_choroid) +
  geom_hline(yintercept = 0.3, linetype = "dashed", color = "red") + 
  theme_bw + labels_standard + labels_rotate_x

p11 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# Antisense mapping
p <- ggplot(metrics_summary, aes(x = sample_name, y = AntisenseMapping_pct, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Reads Mapped Antisense to Genes", 
       x = "Samples", y = "Antisense Mapping (%)") +
  scale_fill_manual(values = col_choroid) +
  geom_hline(yintercept = 0.1, linetype = "dashed", color = "red") + 
  theme_bw + labels_standard + labels_rotate_x

p12 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())
```

```{r valid-barcodes, fig.dim = c(13,6)}
# Valid barcodes
p <- ggplot(metrics_summary, aes(x = sample_name, y = ValidBarcodes_pct, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Valid Barcodes", 
       x = "Samples", y = "Valid Barcodes (%)") +
  scale_fill_manual(values = col_choroid) +
  geom_hline(yintercept = 0.75, linetype = "dashed", color = "red") + 
  theme_bw + labels_standard + labels_rotate_x

p13 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())

# Valid UMIs
p <- ggplot(metrics_summary, aes(x = sample_name, y = ValidUMI_pct, fill = tissue)) +
  geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
  labs(title = "Valid UMIs", 
       x = "Samples", y = "Valid UMIs (%)") +
  scale_fill_manual(values = col_choroid) +
  theme_bw + labels_standard + labels_rotate_x

p14 <- add_info_bar(p, info_type = "tissue", label = FALSE) + scale_y_continuous(labels = label_comma(), breaks = pretty_breaks())
```

```{r}
# wrap plots
(p1 + p2 + p3 + p4 + p5 + p6 + p7 + p8 + p9 + p10 + p11 + p12 + p13 + p14) + plot_layout(nrow = 3, guides = "collect")

# remove objects
rm(metrics_summary)
```

### GEX QC metrics

#### Before filtering {.tabset}

```{r}
# Number of Features
p1 <- VlnPlot(gex_choroid, features = "nFeature_RNA", split.by = "tissue", group.by = "sample_name",
        cols = col_choroid, pt.size = 0.00, raster = FALSE, y.max = 30000) + #%>%
  #add_info_bar(method = "add", info_type = "tissue", label = FALSE, info = gex_choroid) +
  labs(title = "Number of Features", subtitle = "Before Filtering", x = "sample_name") +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank()) +
  coord_cartesian(ylim = c(0, 10000)) +
  NoLegend() + labels_standard

# Number of Counts
p2 <- VlnPlot(gex_choroid, features = "nCount_RNA", split.by = "tissue", group.by = "sample_name",
        cols = col_choroid, pt.size = 0.00, raster = FALSE, log = TRUE) + #%>%
  #add_info_bar(method = "add", info_type = "tissue", info = gex_choroid, label = FALSE) +
  labs(title = "Number of Counts - Before Filtering",
       x = "Sample Name") +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank()) +
  NoLegend() + labels_standard +
  scale_y_continuous(trans = "log10", 
                     breaks = scales::trans_breaks("log10", function(x) 10^x),
                     labels = scales::trans_format("log10", scales::math_format(10^.x)))

# Percent Mitochondrial
p3 <- VlnPlot(gex_choroid, features = "percent.mt", split.by = "subject_id", group.by = "sample_name",
        cols = col_subj, pt.size = 0.00, raster = FALSE) + #%>%
  #add_info_bar(method = "add", info_type = "tissue", info = gex_choroid, label = FALSE) +
  labs(title = "Percent Mitochondrial", subtitle = "Before Filtering", x = "Sample Name") +
  scale_y_continuous(labels = label_percent(scale = 1), breaks = seq(0, 100, by = 10)) +
  coord_cartesian(ylim = c(0, 60)) +
  geom_hline(yintercept = 15, linetype = "dashed", color = "red") +
  labels_standard + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank())

# ribosomal percentage
p4 <- VlnPlot(gex_choroid, features = "percent.ribo", split.by = "tissue", group.by = "sample_name",
        cols = col_choroid, pt.size = 0.00, raster = FALSE) + #%>%
  #add_info_bar(method = "add", info_type = "tissue", info = gex_choroid, label = FALSE) +
  labs(title = "Percent Ribosomal", subtitle = "Before Filtering", x = "Sample Name") +
  scale_y_continuous(labels = label_percent(scale = 1), breaks = seq(0, 100, by = 5)) +
  coord_cartesian(ylim = c(0, 20)) +
  NoLegend() + labels_standard

# empty droplets or multiplets
p5 <- FeatureScatter(gex_choroid, feature1 = "nCount_RNA", feature2 = "nFeature_RNA",
               pt.size = 0.5, group.by = "tissue", cols = col_choroid, raster = FALSE) +
  labs(title = "Multiplets (by Counts and Features)") +
  NoLegend()

# mitochrodrial percentage
p6 <- FeatureScatter(gex_choroid, feature1 = "nCount_RNA", feature2 = "percent.mt",
               pt.size = 0.5, group.by = "tissue", cols = col_choroid, raster = FALSE) +
  scale_x_continuous(labels = label_number(scale = 1, big.mark = ",")) +
  coord_cartesian(xlim = c(0, 150000)) +
  labs(title = "Mitochondrial Percentage") +
  NoLegend()
```

```{r}
# violin plots
p1 / p2 / p3 / p4

# scatter plots
p5 / p6
```

#### Apply filtering

```{r}
# values based on previous QC
gex_choroid <- subset(gex_choroid, subset = nFeature_RNA > 300 & percent.mt < 20)
```

#### After filtering {.tabset}

```{r}
# Number of Features
p1 <- VlnPlot(gex_choroid, features = "nFeature_RNA", split.by = "tissue", group.by = "sample_name",
        cols = col_choroid, pt.size = 0.00, raster = FALSE, y.max = 10000) + #%>%
  labs(title = "Number of Features", subtitle = "After Filtering", x = "sample_name") +
  #theme(axis.title.x = element_blank(), axis.text.x = element_blank()) +
  labels_standard + NoLegend()

# Number of Counts
p2 <- VlnPlot(gex_choroid, features = "nCount_RNA", split.by = "tissue", group.by = "sample_name",
        cols = col_choroid, pt.size = 0.00, raster = FALSE, log = TRUE) + #%>%
  #add_info_bar(method = "add", info_type = "tissue", info = gex_choroid, label = FALSE) +
  labs(title = "Number of Counts", subtitle = "After Filtering", x = "Sample Name") +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank()) +
  NoLegend() + labels_standard +
  scale_y_continuous(trans = "log10", 
                     breaks = scales::trans_breaks("log10", function(x) 10^x),
                     labels = scales::trans_format("log10", scales::math_format(10^.x)))

# Percent Mitochondrial
p3 <- VlnPlot(gex_choroid, features = "percent.mt", split.by = "subject_id", group.by = "sample_name",
        cols = col_subj, pt.size = 0.00, raster = FALSE) + #%>%
  #add_info_bar(method = "add", info_type = "tissue", info = gex_choroid, label = FALSE) +
  labs(title = "Percent Mitochondrial", subtitle = "After Filtering", x = "Sample Name") +
  scale_y_continuous(labels = label_percent(scale = 1), breaks = seq(0, 100, by = 10)) +
  labels_standard + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank())

# ribosomal percentage
p4 <- VlnPlot(gex_choroid, features = "percent.ribo", split.by = "tissue", group.by = "sample_name",
        cols = col_choroid, pt.size = 0.00, raster = FALSE) + #%>%
  #add_info_bar(method = "add", info_type = "tissue", info = gex_choroid, label = FALSE) +
  labs(title = "Percent Ribosomal",  subtitle = "After Filtering", x = "Sample Name") +
  scale_y_continuous(labels = label_percent(scale = 1), breaks = seq(0, 100, by = 5)) +
  coord_cartesian(ylim = c(0, 20)) +
  NoLegend() + labels_standard

# empty droplets or multiplets
p5 <- FeatureScatter(gex_choroid, feature1 = "nCount_RNA", feature2 = "nFeature_RNA",
               pt.size = 0.5, group.by = "tissue", cols = col_choroid, raster = FALSE) +
  scale_x_continuous(labels = label_number(scale = 1, big.mark = ",")) +
  labs(title = "Multiplets (by Counts and Features)") +
  NoLegend()

# mitochrodrial percentage
p6 <- FeatureScatter(gex_choroid, feature1 = "nCount_RNA", feature2 = "percent.mt",
               pt.size = 0.5, group.by = "tissue", cols = col_choroid, raster = FALSE) +
  scale_x_continuous(labels = label_number(scale = 1, big.mark = ",")) +
  coord_cartesian(xlim = c(0, 150000)) +
  labs(title = "Mitochondrial Percentage") + 
  NoLegend()
```

```{r}
# violin plots
p1 / p2 / p3 / p4

# scatter plots
p5 / p6
```

```{r}
# check number of cells after QC
gex_choroid@meta.data %>% 
  group_by(subject_id, HIV_status, tissue) %>% 
  summarize(n_cells = n()) %>% 
  arrange(HIV_status) %>%
  kable() %>% kable_styling("striped")
```